[s] command.68k = 
stdmain,shmain,shell,shswi,sherr,shmem,shsym,shtools,shmsgs,shstruct,cmdtab,
xcls,xecho,xexit,xlist,xlogoff,xorder,xpath,xpause,xprompt,xrem,
break,breakmsg,ctty,chdir,chdirmsg,define,defmsg,utverify,vfymsg,
erase,eramsg,cancel,cancemsg,mkdir,mkdirmsg,rmdir,rmdirmsg,
assign,asnmsgs,security,securmsg,
dvrunit,dvrlink,dvrload,dvrunlk,dvrtools,
40pro.l68,40pro.l68,errlib.l68,ccutls.l68,ccrtl.l68,
ccmsgs.l68,util68k.l68

