
/******************************************************************************
* BASPAG.H 							Version 1.0.02
*******************************************************************************
* Copyright (c) 1985, Digital Research, Inc. All Rights Reserved. The Software
* Code contained in this listing is proprietary to Digital Research, Inc.,
* Monterey, California and is covered by U.S. and other copyright protection.
* Unauthorized copying, adaptation, distribution, use or display is prohibited
* and may be subject to civil and criminal penalties.  Disclosure to others is
* prohibited.  For the terms and conditions of software code use refer to the
* appropriate Digital Research License Agreement.
*******************************************************************************
* Version   Date   Who  Description
* ======= ======== ===  =======================================================
* v1.0.02 09/05/85 FRH	Remove DRL, NRL
* v1.0.01 08/18/85 FRH  No more ZLR
* v1.0.00 05/28/85	Concurrent DOS 286 1.0 Release Version
******************************************************************************/

EXTERN PD *rlr, *thrdrt;
EXTERN EVB *dlr, *plr;
EXTERN MD *mfl, *allocp;
EXTERN WORD elinkoff, pthrdoff;
EXTERN SPB *bdsync, *qsync, *memsync, *slr;
EXTERN BDA *bdap;
EXTERN LONG curpid;
EXTERN UWORD indisp;
linkoff, pthrdoff;
EXTERN SPB *bdsync, *qsync, *
sync, *slr;
EXTERN BDA *bdap;
EXTERN LONG curpid;
EXTERN UWORD indisp;
linkoff, pthrdoff;
EXTERN SPB *bdsync, *qsync, *